name: artwork-indexer tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      db:
        image: metabrainz/musicbrainz-test-database:production
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        . .venv/bin/activate
        pip install -r requirements.txt
    - name: Run flake8
      run: |
        . .venv/bin/activate
        flake8 *.py tests/*.py --count --show-source --statistics
    - name: Run tests
      run: |
        . .venv/bin/activate
        cp config.tests.example.ini config.tests.ini
        export PGHOST=localhost
        export PGPORT=5432
        export DROPDB_COMMAND='sudo -E -H -u postgres dropdb'
        ./run_tests.sh
