name: artwork-indexer tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      db:
        image: metabrainz/musicbrainz-test-database:production
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Add ~/.local/bin to PATH
      run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --user 'pipx==1.7.1'
        pipx install 'poetry==1.8.3'
        poetry install
    - name: Run flake8
      run: |
        poetry run flake8 *.py tests/*.py --count --show-source --statistics
    - name: Run tests
      run: |
        cp config.tests.example.ini config.tests.ini
        export PGHOST=localhost
        export PGPORT=5432
        export DROPDB_COMMAND='sudo -E -H -u postgres dropdb'
        ./run_tests.sh
